# Dockerfile
FROM mysql:8.0

# 文字コードの設定
ENV LANG="ja_JP.UTF-8"
ENV LC_ALL="ja_JP.UTF-8"
ENV LANGUAGE="ja_JP.UTF-8"

# タイムゾーンの設定
ENV TZ="Asia/Tokyo"

# MySQLの環境変数設定
ENV MYSQL_USER=jboy
ENV MYSQL_PASSWORD=1234qw
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=myapp

# 外部接続を許可するための設定
CMD ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--bind-address=0.0.0.0"]